import Head from 'next/head';
import Image from 'next/image';
import {Navigation} from "../components/Navigation";

// Images
import Avatar from '../public/images/avatar.jpg';
import Youtube from '../public/images/projects/Youtube Channel.jpg';
import Doni_Spot from '../public/images/projects/Doni Spot.png';

import { ChevronDoubleDownIcon } from "@heroicons/react/solid";
import {Card} from "../components/Card";

import ICard from '../interfaces/ICard';

export default function Home() {

    const personalProjects: ICard[] = [
        {
            name: "Doni Spot (Youtube)",
            background: Youtube,
            url: "https://youtube.com/c/donispot",
            description: "My spanish web development channel!"
        },
        {
            name: "Doni Spot (Web)",
            background: Doni_Spot,
            url: "https://donispot.com",
            description: "Online courses marketplace in Spanish!"
        },
    ];

    const sampleProjects: ICard[] = [

    ];

    return (
        <div>
            <Head>
                <title>Doni Dominguez Hernandez | Software Engineer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navigation />

                <section id="about" className="md:h-screen h-full mt-14 flex flex-col md:flex-row bg-gray-900 justify-center items-center text-white p-10">
                    <div className="md:w-1/2 md:pl-14 md:pr-4 text-center md:text-justify">
                        <h1 className="font-Nicollast font-bold text-7xl md:text-9xl" style={{ textShadow: "1px 2px 3px rgba(0,0,0,0.5)" }}>Hi, I´m <span className="text-yellow-400">Doni!</span></h1>
                        <p className="font-Montserrat-Thin py-5 mb-10 text-2xl">
                            {/* eslint-disable-next-line react/no-unescaped-entities */}
                            I'm a <span className="font-Montserrat-Bold text-yellow-500">software engineer</span> specialized in both <span className="font-Montserrat-Bold text-yellow-500">front-end</span> and <span className="font-Montserrat-Bold text-yellow-500">back-end</span>. I'm a passionate about web development and I really love Javascript. I live in Cuba and I'm currently looking for work outside my country.
                        </p>
                        <a href="#" className="bg-yellow-500 font-Montserrat-Bold text-white p-4 rounded-md hover:bg-gray-900 border-gray-900 hover:border-yellow-500 border transition-all duration-150 delay-150">
                            Download cv
                        </a>
                    </div>
                    <div className="md:w-1/2 mt-16 flex justify-center items-center">
                        <div>
                            <Image src={Avatar} className="rounded-full" width={500} height={500} alt="Doni Hernández"/>
                        </div>
                    </div>
                </section>

                <section id="skills" className="md:h-screen text-center flex flex-col justify-center items-center md:p-32 p-16">
                    <h2 className="text-7xl md:text-9xl font-bold font-Nicollast">My <span className="text-yellow-400">Skills</span></h2>

                    <div className="flex md:flex-row flex-col md:justify-between justify-center items-center h-full mt-10 md:mt-0 md:space-x-6 md:space-y-0 space-y-4">
                        <div className="border border-yellow-300 w-full rounded-lg p-5" style={{ maxHeight: "600px", height: "400px" }}>
                            <h3 className="font-Montserrat-Bold text-2xl">Front-End</h3>

                            <ul className="mt-6 font-Montserrat-Light">
                                <li className="border-b border-gray-200 pb-2">
                                    HTML5
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    CSS3
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    Javascript
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    React / Next.js
                                </li>
                                <li className="pt-2">
                                    Vue / Nuxt.js
                                </li>
                            </ul>
                        </div>

                        <div className="border border-yellow-300 w-full rounded-lg p-5" style={{ maxHeight: "600px", height: "400px" }}>
                            <h3 className="font-Montserrat-Bold text-2xl">Backend-End</h3>

                            <ul className="mt-6 font-Montserrat-Light ">
                                <li className="border-b border-gray-200 pb-2">
                                    PHP / Laravel
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    Node.js / Express / Strapi / AWS Serverless
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    Graphql
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    MongoDB
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    DynamoDB
                                </li>
                                <li className="pt-2">
                                    MySQL / PostgreSQL
                                </li>
                            </ul>
                        </div>

                        <div className="border border-yellow-300 w-full rounded-lg p-5" style={{ maxHeight: "600px", height: "400px" }}>
                            <h3 className="font-Montserrat-Bold text-2xl">Complementary Skills</h3>

                            <ul className="mt-6 font-Montserrat-Light">
                                <li className="border-b border-gray-200 pb-2">
                                    Git / Github / Gitlab
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    Windows OS
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    Linux / Debian
                                </li>
                                <li className="border-b border-gray-200 pb-2 pt-2">
                                    Spanish (Native) / English (Fluent)
                                </li>
                                <li className="pt-2">
                                    Digital Marketing / SEO
                                </li>
                            </ul>
                        </div>
                    </div>

                    <a href="#projects" className="mt-6">
                        <ChevronDoubleDownIcon className="md:h-14 md:w-14 h-10 w-10 hover:text-yellow-400 cursor-pointer animate-bounce transition-all duration-150 delay-150"/>
                    </a>


                </section>

                <section id="projects" className="md:h-full text-center bg-gray-900 text-white md:pt-32 md:pb-16 p-16">
                    <h2 className="text-7xl md:text-9xl font-bold font-Nicollast">My <span className="text-yellow-400">Projects</span></h2>

                    <div className="flex flex-col md:flex-row mt-10">
                        <div className="border-b md:w-1/2 md:border-r md:border-b-0 border-gray-400 p-8">
                            <h3 className="font-Montserrat-Bold text-3xl">Sample Projects</h3>
                            <div className="grid md:grid-cols-2 grid-cols-1 gap-6 mt-14">
                                <Card name="Doni Spot" background={Youtube} url="https://youtube.com/c/donispot" description="Lorem ipsum dolor sit amet, consectetur adipisicing elit." />
                                <Card name="Doni Spot" background={Youtube} url="https://youtube.com/c/donispot" description="Lorem ipsum dolor sit amet, consectetur adipisicing elit." />
                                <Card name="Doni Spot" background={Youtube} url="https://youtube.com/c/donispot" description="Lorem ipsum dolor sit amet, consectetur adipisicing elit." />
                            </div>
                        </div>
                        <div className="md:w-1/2 p-8">
                            <h3 className="font-Montserrat-Bold text-3xl">Personal Projects</h3>
                            <div className="grid md:grid-cols-2 grid-cols-1 gap-6 mt-14">
                                {
                                    personalProjects.map((project, index) => {
                                        return <Card key={index} name={project.name} background={project.background} url={project.url} description={project.description} />
                                    })
                                }
                            </div>
                        </div>
                    </div>

                    <a href="#contact" className="mt-14 flex justify-center items-center">
                        <ChevronDoubleDownIcon className="md:h-14 md:w-14 h-10 w-10 hover:text-yellow-400 cursor-pointer animate-bounce transition-all duration-150 delay-150"/>
                    </a>

                </section>

                <section id="contact" className="md:h-screen text-center flex flex-col justify-center items-center md:p-32 p-16">
                    <h2 className="text-7xl md:text-9xl font-bold font-Nicollast">Contact <span className="text-yellow-400">Me!</span></h2>
                    <form className="flex flex-col justify-center items-center w-full space-y-5">
                        <input className="border border-gray-300 rounded-lg p-4 w-1/4" type="text" placeholder="your name is..." />
                        <input className="border border-gray-300 rounded-lg p-4 w-1/4" type="email" placeholder="your email is..." />
                        <textarea className="border border-gray-300 rounded-lg p-4 w-1/4" placeholder="message"/>
                        <button className="md:w-1/4 bg-yellow-500 font-Montserrat-Bold text-white p-2 rounded-md hover:bg-white border-white hover:border-yellow-400 hover:text-gray-900 border transition-all duration-150 delay-150" type="submit">send</button>
                    </form>
                </section>

            </main>

            <footer>
                <p>{ Date.now() }</p>
            </footer>
        </div>
    )
}
